name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.11.2-slim-bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r dev-requirements.txt
      - name: Lint with isort
        run: isort --check-only open_banking_archiver
      - name: Lint with flake8
        run: flake8 open_banking_archiver
      - name: Lint with black
        run: black --check open_banking_archiver
      - name: Lint with mypy
        run: mypy open_banking_archiver